"""Work order: the document that tells a vendor what to deliver, by when, and for how much.

A vendor's invoice is checked against it, so it carries the number the
invoice must quote.
"""

import io
from datetime import date
from xml.sax.saxutils import escape

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.config import settings
from app.models import Project, ProjectVendor
from app.services.agent_mou import MARGIN, require_company_name
from app.services.invoice_workflow import format_inr

# Section 194C: TDS on payments to contractors (companies and firms).
CONTRACTOR_TDS_RATE = 2.0


def _money(amount: float) -> str:
    # The built-in PDF fonts have no rupee glyph, so print "Rs." rather than a blank box.
    return format_inr(amount).replace("₹", "Rs. ")


def _date(day: date | None) -> str:
    return day.strftime("%d %b %Y") if day else "-"


def work_order_terms(project: Project, pv: ProjectVendor) -> list[tuple[str, str]]:
    """(label, value) rows of the work order, in print order."""
    return [
        ("Project", f"{project.code} - {project.title}"),
        ("Brand", project.brand or "-"),
        ("Share of the work", f"{pv.work_percent:g}%"),
        ("Agreed cost", f"{_money(pv.agreed_cost)} plus GST as applicable"),
        ("Start date", _date(project.start_date)),
        ("End date", _date(project.end_date)),
        ("Report due by", _date(project.expected_report_date)),
    ]


def work_order_conditions(pv: ProjectVendor) -> list[str]:
    return [
        f"Quote work order number {pv.work_order_number} on every invoice for this work. "
        "Invoices without it, or above the agreed cost, will not be paid until corrected.",
        "The total invoiced for this work order must not exceed the agreed cost unless we agree a change in writing.",
        f"Tax will be deducted at source as the law requires (currently {CONTRACTOR_TDS_RATE:g}% for companies and "
        "firms under section 194C), and the certificate will be issued.",
        "Payment is made by bank transfer to the account on our records after the report is received and accepted.",
        "Information about the project and the client is confidential.",
    ]


def render_work_order_pdf(project: Project, pv: ProjectVendor) -> bytes:
    company = require_company_name("A work order")
    vendor = pv.vendor
    styles = getSampleStyleSheet()
    body = ParagraphStyle("body", parent=styles["BodyText"], fontSize=9.5, leading=13, spaceAfter=4)
    label = ParagraphStyle("label", parent=body, textColor="#555555")
    heading = ParagraphStyle("heading", parent=body, fontName="Helvetica-Bold", spaceBefore=8, spaceAfter=2)
    title = ParagraphStyle("title", parent=styles["Title"], fontSize=16, spaceAfter=2)
    subtitle = ParagraphStyle("subtitle", parent=body, alignment=1, textColor="#555555", spaceAfter=12)
    small = ParagraphStyle("small", parent=body, fontSize=8, textColor="#777777")

    def para(text: str, style: ParagraphStyle = body) -> Paragraph:
        return Paragraph(escape(text), style)

    parties = Table([[
        [para("From", label), para(company), para(settings.company_address or ""),
         para(f"GSTIN {settings.company_gstin}" if settings.company_gstin else "")],
        [para("To", label), para(vendor.business_name), para(vendor.email),
         para(f"GSTIN {vendor.gst_number}" if vendor.gst_number else ""),
         para(f"PAN {vendor.pan}" if vendor.pan else "")],
    ]], colWidths="*")
    parties.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP")]))

    terms = Table([[para(k, label), para(v)] for k, v in work_order_terms(project, pv)], colWidths=[45 * mm, None])
    terms.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LINEBELOW", (0, 0), (-1, -1), 0.25, "#dddddd"),
    ]))

    story = [
        para("Work Order", title),
        para(f"{pv.work_order_number} · {_date(pv.work_order_date)}", subtitle),
        parties,
        Spacer(1, 6 * mm),
        terms,
        para("Scope of work", heading),
        para(project.description or "As discussed and agreed for this project."),
        para("Conditions", heading),
    ]
    story += [para(f"{i}. {text}") for i, text in enumerate(work_order_conditions(pv), start=1)]
    story += [Spacer(1, 14 * mm), para("_" * 34), para(f"For {company}"), para("Authorised signatory"),
              Spacer(1, 8 * mm), para("Generated by Project O2.", small)]

    buffer = io.BytesIO()
    SimpleDocTemplate(
        buffer, pagesize=A4, leftMargin=MARGIN, rightMargin=MARGIN, topMargin=MARGIN, bottomMargin=MARGIN,
        title=f"Work order {pv.work_order_number}", author=company,
    ).build(story)
    return buffer.getvalue()


def work_order_filename(pv: ProjectVendor) -> str:
    return f"{(pv.work_order_number or 'work-order').replace('/', '-')}.pdf"
