"""initial schema

Revision ID: c1a551a580e0
Revises: 
Create Date: 2026-06-26 11:53:00.116456
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c1a551a580e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_name', sa.String(length=120), nullable=True),
    sa.Column('actor_role', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('file_path', sa.String(length=300), nullable=True),
    sa.Column('bank_name', sa.String(length=160), nullable=True),
    sa.Column('account_number', sa.String(length=40), nullable=True),
    sa.Column('uploaded_by', sa.String(length=120), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('gst_number', sa.String(length=30), nullable=True),
    sa.Column('coi', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_business_name'), 'clients', ['business_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN_CEO', 'CFO', 'FINANCE_MANAGER', 'FINANCE_EXECUTIVE', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gst_number', sa.String(length=30), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('bank_account_holder', sa.String(length=160), nullable=True),
    sa.Column('bank_name', sa.String(length=160), nullable=True),
    sa.Column('account_number', sa.String(length=40), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('tax_applicable', sa.Boolean(), nullable=False),
    sa.Column('compliance_documents', sa.String(length=300), nullable=True),
    sa.Column('annual_service_contract', sa.String(length=300), nullable=True),
    sa.Column('approval_status', sa.Enum('PENDING', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', name='vendorapprovalstatus'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_business_name'), 'vendors', ['business_name'], unique=False)
    op.create_table('client_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=60), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('taxable_value', sa.Float(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=False),
    sa.Column('gst_amount', sa.Float(), nullable=False),
    sa.Column('cgst', sa.Float(), nullable=False),
    sa.Column('sgst', sa.Float(), nullable=False),
    sa.Column('igst', sa.Float(), nullable=False),
    sa.Column('is_interstate', sa.Boolean(), nullable=False),
    sa.Column('tds_applicable', sa.Boolean(), nullable=False),
    sa.Column('tds_rate', sa.Float(), nullable=False),
    sa.Column('expected_tds', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('amount_received', sa.Float(), nullable=False),
    sa.Column('amount_pending', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PENDING', 'PARTIALLY_PAID', 'FULLY_PAID', 'OVERDUE', 'CANCELLED', 'DISPUTED', 'RECONCILED', name='invoicestatus'), nullable=False),
    sa.Column('gst_status', sa.Enum('PENDING_COLLECTION', 'COLLECTED', 'PAYMENT_PENDING', 'PAID', 'RECONCILED', name='gststatus'), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supporting_document', sa.String(length=300), nullable=True),
    sa.Column('internal_remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_invoices_invoice_number'), 'client_invoices', ['invoice_number'], unique=True)
    op.create_table('vendor_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('scope_of_work', sa.Text(), nullable=True),
    sa.Column('agreed_cost', sa.Float(), nullable=False),
    sa.Column('vendor_margin', sa.Float(), nullable=False),
    sa.Column('allocation_percent', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('expected_report_date', sa.Date(), nullable=True),
    sa.Column('internal_owner', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'REPORT_DUE', 'COMPLETED', 'ON_HOLD', name='allocationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('bank_reference', sa.String(length=120), nullable=True),
    sa.Column('payment_mode', sa.Enum('NEFT', 'RTGS', 'IMPS', 'UPI', 'CHEQUE', 'CASH', 'OTHER', name='paymentmode'), nullable=False),
    sa.Column('tds_deducted', sa.Float(), nullable=False),
    sa.Column('gst_component', sa.Float(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('attachment', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['client_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(length=60), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('invoice_amount', sa.Float(), nullable=False),
    sa.Column('gst_amount', sa.Float(), nullable=False),
    sa.Column('tds_applicable', sa.Boolean(), nullable=False),
    sa.Column('tds_rate', sa.Float(), nullable=False),
    sa.Column('tds_amount', sa.Float(), nullable=False),
    sa.Column('net_payable', sa.Float(), nullable=False),
    sa.Column('report_submitted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PENDING', 'PARTIALLY_PAID', 'FULLY_PAID', 'OVERDUE', 'CANCELLED', 'DISPUTED', 'RECONCILED', name='invoicestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['vendor_allocations.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_invoices_invoice_number'), 'vendor_invoices', ['invoice_number'], unique=False)
    op.create_table('vendor_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('allocation_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('reporting_period', sa.String(length=80), nullable=True),
    sa.Column('report_type', sa.String(length=80), nullable=True),
    sa.Column('uploaded_file', sa.String(length=300), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('internal_reviewer', sa.String(length=120), nullable=True),
    sa.Column('review_status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'SENT_TO_CLIENT', name='reportreviewstatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['vendor_allocations.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('delivery_status', sa.String(length=40), nullable=False),
    sa.Column('sent_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['vendor_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payee_name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('vendor_invoice_id', sa.Integer(), nullable=True),
    sa.Column('tax_deductions', sa.Float(), nullable=False),
    sa.Column('net_payable', sa.Float(), nullable=False),
    sa.Column('bank_details', sa.Text(), nullable=True),
    sa.Column('supporting_documents', sa.String(length=300), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED_CFO', 'CFO_APPROVED', 'CFO_REJECTED', 'SUBMITTED_CEO', 'CEO_APPROVED', 'CEO_REJECTED', 'PAYMENT_READY', 'PAYMENT_RELEASED', 'PAYMENT_VERIFIED', name='approvalstatus'), nullable=False),
    sa.Column('cfo_comment', sa.Text(), nullable=True),
    sa.Column('ceo_comment', sa.Text(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_invoice_id'], ['vendor_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('approver_name', sa.String(length=120), nullable=False),
    sa.Column('approver_role', sa.String(length=40), nullable=False),
    sa.Column('decision', sa.String(length=60), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['payment_approvals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('utr_reference', sa.String(length=120), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('counterparty', sa.String(length=200), nullable=True),
    sa.Column('verification_status', sa.Enum('NOT_VERIFIED', 'STATEMENT_UPLOADED', 'AUTO_MATCHED', 'MANUALLY_MATCHED', 'MISMATCH', 'RECONCILED', name='verificationstatus'), nullable=False),
    sa.Column('matched_payment_id', sa.Integer(), nullable=True),
    sa.Column('matched_approval_id', sa.Integer(), nullable=True),
    sa.Column('match_note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_approval_id'], ['payment_approvals.id'], ),
    sa.ForeignKeyConstraint(['matched_payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['bank_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_transactions')
    op.drop_table('approval_actions')
    op.drop_table('payment_approvals')
    op.drop_table('email_logs')
    op.drop_table('vendor_reports')
    op.drop_index(op.f('ix_vendor_invoices_invoice_number'), table_name='vendor_invoices')
    op.drop_table('vendor_invoices')
    op.drop_table('payments')
    op.drop_table('vendor_allocations')
    op.drop_index(op.f('ix_client_invoices_invoice_number'), table_name='client_invoices')
    op.drop_table('client_invoices')
    op.drop_index(op.f('ix_vendors_business_name'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clients_business_name'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('bank_statements')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
